# Generated by Django 6.1 on 2026-08-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingObject',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('tool', models.CharField(choices=[('pen', 'Pen'), ('eraser', 'Eraser')], max_length=20)),
                ('points', models.JSONField()),
                ('stroke', models.CharField(default='#df4b26', max_length=20)),
                ('stroke_width', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_objects', to='drawing.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
