# Generated by Django 6.1 on 2026-08-29 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_board_drawingobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingobject',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drawingobject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drawingobject',
            name='tool',
            field=models.CharField(max_length=20),
        ),
    ]
